site_name: Frozen Wastes
nav:
  - Home: index.md
  - Story: story
  - Atlas: world/atlas
  - Characters: world/characters
  - Creatures: world/creatures
  - Organizations: world/organizations
extra_css:
  - styles.css
exclude_docs: |
  z_Templates
  scratch_notes
  readme.md
plugins:
  - search
  - include_dir_to_nav:
      file_name_as_title: true
markdown_extensions:
  - attr_list
